bundler_args: --binstubs

rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_ENV='test' RAILS_VERSION=3.2.0"
  - "RAILS_ENV='test' RAILS_VERSION=3.2.19"

script: "bundle exec rake db:drop db:create db:migrate test"
